/**
 * types.ts
 *
 * Shared TypeScript types and interfaces used across all Geez AI Edge
 * Functions and AI agent modules.
 *
 * Naming conventions:
 *   - Request/Response pairs end in ...Request / ...Response
 *   - Database row shapes end in ...Row
 *   - Intermediate agent payloads use descriptive nouns (e.g. StopData)
 */

// ---------------------------------------------------------------------------
// Enumerations (string union types)
// ---------------------------------------------------------------------------

/** Travel style options surfaced in the onboarding Q&A flow. */
export type TravelStyle = "historical" | "food" | "adventure" | "nature" | "mixed";

/** How the user plans to get around during their trip. */
export type TransportMode = "walking" | "public" | "car" | "mixed";

/** Budget tier selected during route generation. */
export type BudgetLevel = "budget" | "mid" | "premium";

/** User's preferred pace throughout the day. */
export type PacePreference = "relaxed" | "normal" | "intense";

/** Place category used in route stops and visited_places. */
export type PlaceCategory =
  | "landmark"
  | "restaurant"
  | "museum"
  | "park"
  | "market"
  | "hidden_gem"
  | "cafe"
  | "shopping"
  | "beach"
  | "viewpoint"
  | "entertainment"
  | "other";

/** Route lifecycle status. */
export type RouteStatus = "draft" | "active" | "completed" | "deleted";

/** Subscription tier. */
export type SubscriptionTier = "free" | "premium";

/** AI provider used for a generation. */
export type AiProvider = "gemini" | "openai" | "anthropic";

// ---------------------------------------------------------------------------
// Route generation — request / response
// ---------------------------------------------------------------------------

/**
 * Body of a POST /functions/v1/generate-route request.
 *
 * Sent by the Flutter app after the user completes the onboarding Q&A flow.
 */
export interface RouteRequest {
  /** Target city name (e.g. "Istanbul"). */
  city: string;
  /** ISO 3166-1 alpha-2 country code or full country name. */
  country: string;
  /** Number of days for the itinerary (1–14). */
  durationDays: number;
  /** Overall travel focus. */
  travelStyle: TravelStyle;
  /** Primary transport mode. */
  transportMode: TransportMode;
  /** Spending level. */
  budgetLevel: BudgetLevel;
  /**
   * Preferred start time for each day in HH:MM (24-hour, local time).
   * Example: "09:00"
   */
  startTime: string;
  /**
   * Free-form additional preferences from the user
   * (e.g. ["avoid tourist traps", "vegetarian food"]).
   */
  preferences?: string[];
  /**
   * BCP-47 language code for the returned content.
   * Defaults to the user's profile language when omitted.
   * Example: "en", "tr"
   */
  language?: string;
}

/**
 * Successful response body from POST /functions/v1/generate-route.
 */
export interface RouteResponse {
  /** UUID of the newly created route row. */
  routeId: string;
  /** Human-readable route title generated by the AI. */
  title: string;
  /** City the route covers. */
  city: string;
  /** Country the route covers. */
  country: string;
  /** Days in the itinerary. */
  durationDays: number;
  /** Ordered daily stop plans. */
  days: DayPlan[];
  /** Which AI model was used (for cost tracking / debugging). */
  aiModelUsed: AiProvider;
  /** Estimated generation cost in USD (logged for cost monitoring). */
  generationCostUsd: number;
  /** ISO 8601 timestamp when the route was created. */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Day plan and stops
// ---------------------------------------------------------------------------

/** One day within a multi-day itinerary. */
export interface DayPlan {
  /** 1-indexed day number. */
  dayNumber: number;
  /** Short thematic title for the day (e.g. "Old City & Bazaars"). */
  title: string;
  /** Ordered list of stops for the day. */
  stops: StopData[];
}

/**
 * A single place/stop in a route.
 *
 * Corresponds to a public.route_stops row plus AI-generated content
 * fields that are populated before the row is persisted.
 */
export interface StopData {
  /** Optional UUID once persisted to the DB. */
  id?: string;
  /** Parent route UUID. */
  routeId?: string;
  /** Day this stop belongs to. */
  dayNumber: number;
  /** Position within the day (1-indexed). */
  stopOrder: number;
  /** Display name of the place. */
  placeName: string;
  /** Google Maps place_id (may be null for non-Google results). */
  placeId?: string;
  /** WGS-84 latitude. */
  latitude?: number;
  /** WGS-84 longitude. */
  longitude?: number;
  /** Place category. */
  category: PlaceCategory;
  // -- AI-generated content --
  /** 2-3 sentence description. */
  description?: string;
  /** Local insider tip. */
  insiderTip?: string;
  /** Interesting fun fact. */
  funFact?: string;
  /** Best time of day to visit (free text). */
  bestTime?: string;
  /** Warnings (closures, crowds, etc.). */
  warnings?: string;
  /** Synthesised summary of Google/travel reviews. */
  reviewSummary?: string;
  // -- Practical info --
  /** Google Maps average star rating. */
  googleRating?: number;
  /** Total number of reviews used in synthesis. */
  reviewCount?: number;
  /** Estimated visit duration in minutes. */
  estimatedDurationMin?: number;
  /** Entry fee display string (e.g. "Free", "€15"). */
  entryFee?: string;
  /** Numeric entry fee amount (in entry_fee_currency). */
  entryFeeAmount?: number;
  /** ISO 4217 currency code for entry_fee_amount. */
  entryFeeCurrency?: string;
  // -- Navigation --
  /** Travel time from the previous stop, in minutes. */
  travelFromPreviousMin?: number;
  /** Transport mode from the previous stop. */
  travelModeFromPrevious?: TransportMode;
  // -- Timing --
  /** Suggested start time as HH:MM. */
  suggestedStartTime?: string;
  /** Suggested end time as HH:MM. */
  suggestedEndTime?: string;
  // -- Gamification --
  /** Discovery points awarded for visiting this stop. */
  discoveryPoints?: number;
}

// ---------------------------------------------------------------------------
// AI / Chat message types
// ---------------------------------------------------------------------------

/** Role in a chat/messages API call. */
export type MessageRole = "user" | "assistant" | "system";

/**
 * A single message in an LLM conversation.
 *
 * Compatible with both the Anthropic Messages API and OpenAI Chat Completions
 * format for the fields we use.
 */
export interface ChatMessage {
  role: MessageRole;
  content: string;
}

// ---------------------------------------------------------------------------
// User context (Memory Agent output)
// ---------------------------------------------------------------------------

/**
 * Aggregated user context assembled by the Memory Agent.
 *
 * Passed to the Research, Route, and Content agents to personalise output.
 */
export interface UserContext {
  /** Supabase Auth user UUID. */
  userId: string;
  /** Snapshot of user_profiles row. */
  profile: UserProfileSnapshot | null;
  /** Snapshot of travel_personas row. */
  persona: TravelPersonaSnapshot | null;
  /** Recently visited places (up to 100). */
  visitedPlaces: VisitedPlaceSnapshot[];
  /** Most recent trip feedback entries (up to 10). */
  recentFeedback: TripFeedbackSnapshot[];
  /** Inferred pace from feedback history. */
  pacePreference: PacePreference;
  /** Strongly preferred activity types derived from feedback. */
  strongPreferences: string[];
}

/** Subset of user_profiles used in context. */
export interface UserProfileSnapshot {
  ageGroup?: string;
  travelCompanion?: string;
  defaultBudget?: BudgetLevel;
  preferredActivities: string[];
  foodPreferences: Record<string, boolean>;
  pacePreference: PacePreference;
  morningPerson: boolean;
  crowdTolerance: "low" | "medium" | "high";
}

/** Subset of travel_personas used in context. */
export interface TravelPersonaSnapshot {
  foodieLevel: number;
  historyBuffLevel: number;
  natureLoverLevel: number;
  adventureSeekerLevel: number;
  cultureExplorerLevel: number;
  discoveryScore: number;
  explorerTier: string;
}

/** Subset of visited_places used in context. */
export interface VisitedPlaceSnapshot {
  placeId?: string;
  placeName: string;
  city: string;
  country: string;
  category?: string;
  userRating?: number;
  visitedAt?: string;
}

/** Subset of trip_feedback used in context. */
export interface TripFeedbackSnapshot {
  routeId: string;
  overallRating?: number;
  paceFeedback?: "too_intense" | "just_right" | "too_slow";
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Error and rate-limit response types
// ---------------------------------------------------------------------------

/**
 * Canonical JSON error envelope returned by all Edge Functions on failure.
 *
 * { "error": { "code": "...", "message": "...", "details"?: ... } }
 */
export interface ErrorResponse {
  error: {
    /** Machine-readable error code. */
    code: string;
    /** Human-readable explanation. */
    message: string;
    /** Optional structured detail (e.g. validation errors). */
    details?: unknown;
  };
}

/**
 * Additional headers and body fields present on 429 Too Many Requests
 * responses.
 */
export interface RateLimitInfo {
  /** Monthly route limit for the user's tier. */
  limit: number;
  /** Routes remaining this month (0 when the 429 fires). */
  remaining: number;
  /** ISO 8601 timestamp when the counter resets (first of next month). */
  resetAt: string;
}

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

/**
 * Cache key components for AI route responses.
 *
 * Canonical key: `${city}:${country}:${travelStyle}:${budgetLevel}:${transportMode}:${language}`
 * TTL: 7 days (604 800 seconds).
 *
 * country is included so that city names that appear in multiple countries
 * (e.g. "Victoria" in Canada vs. Seychelles) never collide.
 */
export interface RouteCacheKey {
  city: string;
  /** ISO 3166-1 alpha-2 country code or full country name. */
  country: string;
  travelStyle: TravelStyle;
  budgetLevel: BudgetLevel;
  transportMode: TransportMode;
  language: string;
}

/**
 * Builds the cache lookup key from its components.
 *
 * @param key - The RouteCacheKey parts.
 * @returns A colon-delimited string key.
 */
export function buildCacheKey(key: RouteCacheKey): string {
  return [
    key.city.toLowerCase().trim(),
    key.country.toLowerCase().trim(),
    key.travelStyle,
    key.budgetLevel,
    key.transportMode,
    key.language.toLowerCase(),
  ].join(":");
}
