-- ============================================================
-- 006_ai_cache.sql
-- AI response cache and place vector embeddings.
--
-- Tables:
--   public.ai_route_cache   — server-side cache of generated routes
--   public.place_embeddings — 1536-dim vectors for place similarity search
--
-- Cache key for ai_route_cache:
--   {city}:{country}:{travel_style}:{transport_mode}:{budget_level}:{language}
--   Stored as a single TEXT column with a UNIQUE constraint.
--   TTL enforced by the expires_at column — stale rows are ignored
--   by the Edge Function; a pg_cron job can purge them periodically.
--
-- place_embeddings:
--   Written exclusively by the Research Agent (service_role).
--   Read publicly for similarity queries.
--   IVFFlat index with lists=100 (tune upward for > 1M rows).
-- ============================================================


-- ========================
-- public.ai_route_cache
-- ========================
-- Cached AI-generated route data.
-- Hit ratio target: 40%+ to reduce Claude API costs.
-- Default TTL: 7 days (set by Edge Function on insert).

CREATE TABLE IF NOT EXISTS public.ai_route_cache (
  id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Composite cache key:
  -- Format: "{city}:{country}:{travel_style}:{transport_mode}:{budget_level}:{language}"
  -- Example: "istanbul:tr:food:walking:mid:tr"
  cache_key     TEXT          NOT NULL UNIQUE,

  -- Decomposed key parts (for filtered queries and analytics)
  city          TEXT          NOT NULL,
  country       TEXT          NOT NULL,
  travel_style  TEXT          NOT NULL
                  CHECK (travel_style IN ('historical', 'food', 'adventure', 'nature', 'mixed')),
  transport_mode TEXT         NOT NULL
                  CHECK (transport_mode IN ('walking', 'public', 'car', 'mixed')),
  budget_level  TEXT          NOT NULL
                  CHECK (budget_level IN ('budget', 'mid', 'premium')),
  language      TEXT          NOT NULL DEFAULT 'tr'
                  CHECK (language IN ('tr', 'en')),

  -- Cached payload — full route JSON from the AI Orchestrator
  -- JSONB schema: { stops: [...], city_intro: string, ai_model: string }
  route_data    JSONB         NOT NULL,

  -- Model that generated this cache entry
  ai_model_used TEXT,

  -- TTL / expiry
  expires_at    TIMESTAMPTZ   NOT NULL DEFAULT (now() + INTERVAL '7 days'),

  -- Usage stats (for cache hit analytics)
  hit_count     INT           NOT NULL DEFAULT 0
                  CHECK (hit_count >= 0),
  last_hit_at   TIMESTAMPTZ,

  created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.ai_route_cache            IS 'Server-side AI route cache. TTL = 7 days. Reduces Claude API cost.';
COMMENT ON COLUMN public.ai_route_cache.cache_key  IS 'Composite key: city:country:travel_style:transport_mode:budget_level:language';
COMMENT ON COLUMN public.ai_route_cache.route_data IS 'Full AI-generated route payload. JSONB: {stops:[...], city_intro:string, ai_model:string}';
COMMENT ON COLUMN public.ai_route_cache.expires_at IS 'Edge Function skips rows where expires_at < now(). pg_cron deletes them nightly.';
COMMENT ON COLUMN public.ai_route_cache.hit_count  IS 'Number of times this cache entry was served. Used for TTL tuning analytics.';

CREATE TRIGGER trg_ai_route_cache_set_updated_at
  BEFORE UPDATE ON public.ai_route_cache
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();


-- ========================
-- public.place_embeddings
-- ========================
-- 1536-dimension vector embeddings for place content.
-- Used by the Research Agent for semantic similarity search:
--   "Find places similar to X that this user would like"
-- Embeddings generated by the AI Engineer's embedding pipeline
-- (OpenAI text-embedding-3-small or equivalent 1536-dim model).

CREATE TABLE IF NOT EXISTS public.place_embeddings (
  id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Place identity
  place_id      TEXT          NOT NULL UNIQUE,              -- Google Maps place_id
  place_name    TEXT          NOT NULL,
  city          TEXT          NOT NULL,
  country       TEXT          NOT NULL,
  category      TEXT
                  CHECK (category IN (
                    'landmark', 'restaurant', 'cafe', 'museum',
                    'park', 'market', 'hidden_gem', 'viewpoint',
                    'religious', 'shopping', 'entertainment', 'other'
                  )),

  -- Source text that was embedded (for debugging / re-embedding)
  description   TEXT,

  -- The embedding vector (1536 dimensions)
  embedding     vector(1536),

  -- Embedding model version — if model changes, old rows need re-embedding
  embedding_model TEXT         NOT NULL DEFAULT 'text-embedding-3-small',

  -- Flexible metadata bag
  -- JSONB schema: {google_rating: float, review_count: int, photos: [string], tags: [string]}
  metadata      JSONB         NOT NULL DEFAULT '{}'::jsonb,

  created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.place_embeddings                 IS 'Vector embeddings for place similarity search. Written by Research Agent (service_role only).';
COMMENT ON COLUMN public.place_embeddings.place_id        IS 'Google Maps place_id — globally unique place identifier.';
COMMENT ON COLUMN public.place_embeddings.embedding       IS '1536-dim vector. Query with <=> (cosine distance) operator.';
COMMENT ON COLUMN public.place_embeddings.embedding_model IS 'Model that generated the vector. Re-embed all rows if this changes.';
COMMENT ON COLUMN public.place_embeddings.metadata        IS 'JSONB bag: {google_rating:float, review_count:int, photos:[str], tags:[str]}';

CREATE TRIGGER trg_place_embeddings_set_updated_at
  BEFORE UPDATE ON public.place_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();


-- ========================
-- IVFFlat vector index
-- ========================
-- Cosine distance (<=>) for semantic similarity.
-- lists=100 is appropriate for up to ~1M rows.
-- Increase to 200-300 when row count exceeds 500K.
-- Requires at least (lists * 39) rows to be effective; safe to
-- create on an empty table — Postgres will use seq scan until
-- the threshold is met.
--
-- To query: ORDER BY embedding <=> $1::vector LIMIT 10

CREATE INDEX idx_place_embeddings_vector
  ON public.place_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

COMMENT ON INDEX idx_place_embeddings_vector IS
  'IVFFlat cosine index. lists=100 optimal for <1M rows. Increase to 300 at 500K+ rows.';
